export const mockRegions = [
  { id: 1600, name: 'Kharkov governorate - total population' },
  { id: 1420, name: 'Taurida Governorate - total population' },
]

export const mockData = [
  {
    id: 1,
    langGroup: 'Russian',
    lang: 'Great Russian',
    males: 212688,
    females: 191775,
    regionId: 1420,
  },
  {
    id: 2,
    langGroup: 'Russian',
    lang: 'Ukrainian',
    males: 317167,
    females: 293954,
    regionId: 1420,
  },
  {
    id: 3,
    langGroup: 'Russian',
    lang: 'Belarusian',
    males: 5287,
    females: 4439,
    regionId: 1420,
  },
  {
    id: 4,
    langGroup: 'Polish',
    lang: 'Polish',
    males: 7349,
    females: 2763,
    regionId: 1420,
  },
  {
    id: 5,
    langGroup: 'Other Slavic languages',
    lang: 'Czech',
    males: 1024,
    females: 938,
    regionId: 1420,
  },
  {
    id: 6,
    langGroup: 'Other Slavic languages',
    lang: 'Serbian, Croatian, Slovenian',
    males: 158,
    females: 79,
    regionId: 1420,
  },
  {
    id: 7,
    langGroup: 'Other Slavic languages',
    lang: 'Bulgarian',
    males: 21116,
    females: 20144,
    regionId: 1420,
  },
  {
    id: 8,
    langGroup: 'Lithuanian-Latvian dialects',
    lang: 'Lithuanian',
    males: 163,
    females: 50,
    regionId: 1420,
  },
  {
    id: 9,
    langGroup: 'Lithuanian-Latvian dialects',
    lang: 'Samogitian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 10,
    langGroup: 'Lithuanian-Latvian dialects',
    lang: 'Latvian',
    males: 241,
    females: 49,
    regionId: 1420,
  },
  {
    id: 11,
    langGroup: 'Romance languages',
    lang: 'Moldavian and Romanian',
    males: 1370,
    females: 889,
    regionId: 1420,
  },
  {
    id: 12,
    langGroup: 'Romance languages',
    lang: 'French',
    males: 199,
    females: 265,
    regionId: 1420,
  },
  {
    id: 13,
    langGroup: 'Romance languages',
    lang: 'Italian',
    males: 592,
    females: 529,
    regionId: 1420,
  },
  {
    id: 14,
    langGroup: 'Romance languages',
    lang: 'Spanish and Portuguese',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 15,
    langGroup: 'German',
    lang: 'German',
    males: 39605,
    females: 38700,
    regionId: 1420,
  },
  {
    id: 16,
    langGroup: 'Other Germanic languages',
    lang: 'Swedish',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 17,
    langGroup: 'Other Germanic languages',
    lang: 'Norwegian and Danish',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 18,
    langGroup: 'Other Germanic languages',
    lang: 'Dutch',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 19,
    langGroup: 'Other Germanic languages',
    lang: 'English',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 20,
    langGroup: 'Other Indo-European dialects',
    lang: 'Greek',
    males: 10616,
    females: 7432,
    regionId: 1420,
  },
  {
    id: 21,
    langGroup: 'Other Indo-European dialects',
    lang: 'Albanian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 22,
    langGroup: 'Other Indo-European dialects',
    lang: 'Armenian',
    males: 5094,
    females: 3844,
    regionId: 1420,
  },
  {
    id: 23,
    langGroup: 'Other Indo-European dialects',
    lang: 'Persian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 24,
    langGroup: 'Other Indo-European dialects',
    lang: 'Tajik',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 25,
    langGroup: 'Other Indo-European dialects',
    lang: 'Talysh',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 26,
    langGroup: 'Other Indo-European dialects',
    lang: 'Tat',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 27,
    langGroup: 'Other Indo-European dialects',
    lang: 'Kurdish',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 28,
    langGroup: 'Other Indo-European dialects',
    lang: 'Ossetic',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 29,
    langGroup: 'Other Indo-European dialects',
    lang: 'Hindu',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 30,
    langGroup: 'Other Indo-European dialects',
    lang: 'Gipsy',
    males: 752,
    females: 681,
    regionId: 1420,
  },
  {
    id: 31,
    langGroup: 'Other Indo-European dialects',
    lang: 'Pashto',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 32,
    langGroup: 'Jewish',
    lang: 'Jewish',
    males: 28884,
    females: 26534,
    regionId: 1420,
  },
  {
    id: 33,
    langGroup: 'Kartvelian dialects',
    lang: 'Georgian',
    males: 242,
    females: 18,
    regionId: 1420,
  },
  {
    id: 34,
    langGroup: 'Kartvelian dialects',
    lang: 'Imereti',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 35,
    langGroup: 'Kartvelian dialects',
    lang: 'Mingrelian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 36,
    langGroup: 'Kartvelian dialects',
    lang: 'Svan',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 37,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kabardian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 38,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Circassian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 39,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Abkhaz',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 40,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Chechen',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 41,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Ingush',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 42,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kistin',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 43,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Avar-Andi',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 44,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Dargin',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 45,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kyurin',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 46,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Udi',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 47,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kasi-Kumuk and other Lezgian dialects',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 48,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Lezgian with no breakdown',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 49,
    langGroup: 'Finnish dialects',
    lang: 'Finnish',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 50,
    langGroup: 'Finnish dialects',
    lang: 'Votyak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 51,
    langGroup: 'Finnish dialects',
    lang: 'Karelian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 52,
    langGroup: 'Finnish dialects',
    lang: 'Izhorian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 53,
    langGroup: 'Finnish dialects',
    lang: 'Chud',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 54,
    langGroup: 'Finnish dialects',
    lang: 'Estonian',
    males: 1218,
    females: 992,
    regionId: 1420,
  },
  {
    id: 55,
    langGroup: 'Finnish dialects',
    lang: 'Lappish',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 56,
    langGroup: 'Finnish dialects',
    lang: 'Zyrian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 57,
    langGroup: 'Finnish dialects',
    lang: 'Permyak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 58,
    langGroup: 'Finnish dialects',
    lang: 'Mordovian',
    males: 308,
    females: 67,
    regionId: 1420,
  },
  {
    id: 59,
    langGroup: 'Finnish dialects',
    lang: 'Cheremis',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 60,
    langGroup: 'Finnish dialects',
    lang: 'Vogul',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 61,
    langGroup: 'Finnish dialects',
    lang: 'Ostyak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 62,
    langGroup: 'Finnish dialects',
    lang: 'Hungarian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 63,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Tatar',
    males: 106440,
    females: 90414,
    regionId: 1420,
  },
  {
    id: 64,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Bashkir',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 65,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Misher',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 66,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Teptyar',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 67,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Chuvash',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 68,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Karachay',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 69,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kumyk',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 70,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Nogai',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 71,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Turkish',
    males: 1907,
    females: 290,
    regionId: 1420,
  },
  {
    id: 72,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Karapapak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 73,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Turkmen',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 74,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kyrgyz-Kaissak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 75,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kara-Kirghiz',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 76,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kipchak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 77,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kara-Kalpak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 78,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Sart',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 79,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Uzbek',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 80,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Taranchi',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 81,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kashgar',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 82,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Turkic dialects with no breakdown',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 83,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Yakut',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 84,
    langGroup: 'Mongolian-Buryat dialects',
    lang: 'Kalmyck',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 85,
    langGroup: 'Mongolian-Buryat dialects',
    lang: 'Buryat',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 86,
    langGroup: 'Mongolian-Buryat dialects',
    lang: 'Mongolian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 87,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Samoyed',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 88,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Tungus',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 89,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Manchu',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 90,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Chukchi',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 91,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Koryak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 92,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Kamchadal',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 93,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Yukaghir',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 94,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Chuvanian',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 95,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Eskimo',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 96,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Gilyak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 97,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Ainu',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 98,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Aleut',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 99,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Yenisei Ostyak',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 100,
    langGroup: 'Languages of civilized peoples of the Far East',
    lang: 'Chinese',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 101,
    langGroup: 'Languages of civilized peoples of the Far East',
    lang: 'Korean',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 102,
    langGroup: 'Languages of civilized peoples of the Far East',
    lang: 'Japanese',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 103,
    langGroup: 'Other languages and dialects',
    lang: 'Arabic',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 104,
    langGroup: 'Other languages and dialects',
    lang: 'Aisor (Syro-Chaldean)',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 105,
    langGroup: 'Other languages and dialects',
    lang: 'Other languages',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 106,
    langGroup: 'Persons not specified mother tongue',
    lang: 'Persons not specified mother tongue',
    males: null,
    females: null,
    regionId: 1420,
  },
  {
    id: 107,
    langGroup: 'Remainder (****)',
    lang: 'Remainder (****)',
    males: 384,
    females: 140,
    regionId: 1420,
  },
  {
    id: 1,
    langGroup: 'Russian',
    lang: 'Great Russian',
    males: 225803,
    females: 215133,
    regionId: 1600,
  },
  {
    id: 2,
    langGroup: 'Russian',
    lang: 'Ukrainian',
    males: 1004372,
    females: 1005039,
    regionId: 1600,
  },
  {
    id: 3,
    langGroup: 'Russian',
    lang: 'Belarusian',
    males: 4936,
    females: 5322,
    regionId: 1600,
  },
  {
    id: 4,
    langGroup: 'Polish',
    lang: 'Polish',
    males: 4056,
    females: 1854,
    regionId: 1600,
  },
  {
    id: 5,
    langGroup: 'Other Slavic languages',
    lang: 'Czech',
    males: 143,
    females: 78,
    regionId: 1600,
  },
  {
    id: 6,
    langGroup: 'Other Slavic languages',
    lang: 'Serbian, Croatian, Slovenian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 7,
    langGroup: 'Other Slavic languages',
    lang: 'Bulgarian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 8,
    langGroup: 'Lithuanian-Latvian dialects',
    lang: 'Lithuanian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 9,
    langGroup: 'Lithuanian-Latvian dialects',
    lang: 'Samogitian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 10,
    langGroup: 'Lithuanian-Latvian dialects',
    lang: 'Latvian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 11,
    langGroup: 'Romance languages',
    lang: 'Moldavian and Romanian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 12,
    langGroup: 'Romance languages',
    lang: 'French',
    males: 110,
    females: 208,
    regionId: 1600,
  },
  {
    id: 13,
    langGroup: 'Romance languages',
    lang: 'Italian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 14,
    langGroup: 'Romance languages',
    lang: 'Spanish and Portuguese',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 15,
    langGroup: 'German',
    lang: 'German',
    males: 4504,
    females: 4576,
    regionId: 1600,
  },
  {
    id: 16,
    langGroup: 'Other Germanic languages',
    lang: 'Swedish',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 17,
    langGroup: 'Other Germanic languages',
    lang: 'Norwegian and Danish',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 18,
    langGroup: 'Other Germanic languages',
    lang: 'Dutch',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 19,
    langGroup: 'Other Germanic languages',
    lang: 'English',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 20,
    langGroup: 'Other Indo-European dialects',
    lang: 'Greek',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 21,
    langGroup: 'Other Indo-European dialects',
    lang: 'Albanian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 22,
    langGroup: 'Other Indo-European dialects',
    lang: 'Armenian',
    males: 483,
    females: 132,
    regionId: 1600,
  },
  {
    id: 23,
    langGroup: 'Other Indo-European dialects',
    lang: 'Persian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 24,
    langGroup: 'Other Indo-European dialects',
    lang: 'Tajik',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 25,
    langGroup: 'Other Indo-European dialects',
    lang: 'Talysh',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 26,
    langGroup: 'Other Indo-European dialects',
    lang: 'Tat',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 27,
    langGroup: 'Other Indo-European dialects',
    lang: 'Kurdish',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 28,
    langGroup: 'Other Indo-European dialects',
    lang: 'Ossetic',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 29,
    langGroup: 'Other Indo-European dialects',
    lang: 'Hindu',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 30,
    langGroup: 'Other Indo-European dialects',
    lang: 'Gipsy',
    males: 232,
    females: 193,
    regionId: 1600,
  },
  {
    id: 31,
    langGroup: 'Other Indo-European dialects',
    lang: 'Pashto',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 32,
    langGroup: 'Jewish',
    lang: 'Jewish',
    males: 7007,
    females: 5643,
    regionId: 1600,
  },
  {
    id: 33,
    langGroup: 'Kartvelian dialects',
    lang: 'Georgian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 34,
    langGroup: 'Kartvelian dialects',
    lang: 'Imereti',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 35,
    langGroup: 'Kartvelian dialects',
    lang: 'Mingrelian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 36,
    langGroup: 'Kartvelian dialects',
    lang: 'Svan',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 37,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kabardian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 38,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Circassian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 39,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Abkhaz',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 40,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Chechen',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 41,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Ingush',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 42,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kistin',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 43,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Avar-Andi',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 44,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Dargin',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 45,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kyurin',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 46,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Udi',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 47,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Kasi-Kumuk and other Lezgian dialects',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 48,
    langGroup: 'Dialects of Caucasian hill-peoples',
    lang: 'Lezgian with no breakdown',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 49,
    langGroup: 'Finnish dialects',
    lang: 'Finnish',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 50,
    langGroup: 'Finnish dialects',
    lang: 'Votyak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 51,
    langGroup: 'Finnish dialects',
    lang: 'Karelian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 52,
    langGroup: 'Finnish dialects',
    lang: 'Izhorian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 53,
    langGroup: 'Finnish dialects',
    lang: 'Chud',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 54,
    langGroup: 'Finnish dialects',
    lang: 'Estonian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 55,
    langGroup: 'Finnish dialects',
    lang: 'Lappish',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 56,
    langGroup: 'Finnish dialects',
    lang: 'Zyrian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 57,
    langGroup: 'Finnish dialects',
    lang: 'Permyak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 58,
    langGroup: 'Finnish dialects',
    lang: 'Mordovian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 59,
    langGroup: 'Finnish dialects',
    lang: 'Cheremis',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 60,
    langGroup: 'Finnish dialects',
    lang: 'Vogul',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 61,
    langGroup: 'Finnish dialects',
    lang: 'Ostyak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 62,
    langGroup: 'Finnish dialects',
    lang: 'Hungarian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 63,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Tatar',
    males: 1221,
    females: 137,
    regionId: 1600,
  },
  {
    id: 64,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Bashkir',
    males: 114,
    females: 3,
    regionId: 1600,
  },
  {
    id: 65,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Misher',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 66,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Teptyar',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 67,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Chuvash',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 68,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Karachay',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 69,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kumyk',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 70,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Nogai',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 71,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Turkish',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 72,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Karapapak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 73,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Turkmen',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 74,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kyrgyz-Kaissak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 75,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kara-Kirghiz',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 76,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kipchak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 77,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kara-Kalpak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 78,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Sart',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 79,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Uzbek',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 80,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Taranchi',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 81,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Kashgar',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 82,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Turkic dialects with no breakdown',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 83,
    langGroup: 'Turkish-Tatar dialects',
    lang: 'Yakut',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 84,
    langGroup: 'Mongolian-Buryat dialects',
    lang: 'Kalmyck',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 85,
    langGroup: 'Mongolian-Buryat dialects',
    lang: 'Buryat',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 86,
    langGroup: 'Mongolian-Buryat dialects',
    lang: 'Mongolian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 87,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Samoyed',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 88,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Tungus',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 89,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Manchu',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 90,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Chukchi',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 91,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Koryak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 92,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Kamchadal',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 93,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Yukaghir',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 94,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Chuvanian',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 95,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Eskimo',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 96,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Gilyak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 97,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Ainu',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 98,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Aleut',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 99,
    langGroup: 'Dialects of the other Nothern nations',
    lang: 'Yenisei Ostyak',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 100,
    langGroup: 'Languages of civilized peoples of the Far East',
    lang: 'Chinese',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 101,
    langGroup: 'Languages of civilized peoples of the Far East',
    lang: 'Korean',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 102,
    langGroup: 'Languages of civilized peoples of the Far East',
    lang: 'Japanese',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 103,
    langGroup: 'Other languages and dialects',
    lang: 'Arabic',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 104,
    langGroup: 'Other languages and dialects',
    lang: 'Aisor (Syro-Chaldean)',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 105,
    langGroup: 'Other languages and dialects',
    lang: 'Other languages',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 106,
    langGroup: 'Persons not specified mother tongue',
    lang: 'Persons not specified mother tongue',
    males: null,
    females: null,
    regionId: 1600,
  },
  {
    id: 107,
    langGroup: 'Remainder (****)',
    lang: 'Remainder (****)',
    males: 778,
    females: 239,
    regionId: 1600,
  },
]
